### ISSUE TITLE
autotag tagging same commit over and over again

### ISSUE THREAD

**Issue by mkj28** [pantheon-systems/autotag#17]
(truncating shas)

`git rev-parse HEAD`: deac9d...

but:
`autotag -v`:
```
2019/01/09 23:36:39 Opening repo at /volume/repo/.git                                                                                              
2019/01/09 23:36:39 Parsing repository tags                                                                                                                         
2019/01/09 23:36:39 Checking commits from 3a1901b... to 3a1901b...                                      
2019/01/09 23:36:39 Writing Tag v0.1.10 
```

3a1901b... - is 10 commits old and keeps getting tagged with every new commit to master

**Comment by spheromak** [comment]
this shouldn't be happening on the latest version.  Not sure what version this was that was having this issue, but I assume it was pre 1.x and the move over to the git binary proper for tree traversal should resolve any edges from the pure go implementations
