### ISSUE TITLE
Autotag container image are not working

### ISSUE THREAD

**Issue by piclemx** [pantheon-systems/autotag#26]
You're building our golang app in desbian and you copy it in alpine.

You need to build it in alpine if you want to expose a alpine image

```
FROM golang:alpine AS autotag

ARG AUTOTAG_VERSION=v1.1.4

RUN apk add --no-cache git make

WORKDIR /home

RUN git clone https://github.com/pantheon-systems/autotag.git

WORKDIR /home/autotag

RUN git checkout $AUTOTAG_VERSION

RUN make build
```
use `golang:alpine` instead of the one by `circleci`

**Comment by ghoussard** [comment]
Hello,

I created an image for my personal needs. Feel free to use it : https://hub.docker.com/r/ghoussard/autotag
