### ISSUE TITLE
Support for conventional commits

### ISSUE THREAD

**Issue by KreativeKrise** [pantheon-systems/autotag#27]
Would it be possible to add support for conventional commits?
You will find information on [https://www.conventionalcommits.org/en/v1.0.0/](https://www.conventionalcommits.org/en/v1.0.0/).

This could maybe be implemented by an option to override the default regex.

**Comment by joemiller** [comment]
@KreativeKrise Conventional Commits are supported in v1.2.0 via the `-s conventional` flag. Please report any issues, thanks
