### ISSUE TITLE
make a github action for autotag

### ISSUE THREAD

**Issue by joemiller** [pantheon-systems/autotag#41]
Autotag is generally used in CI/CD pipelines. We should see about providing a GitHub Action that makes it as easy as possible to integrate. 

Bonus points: Make it easy to combine with goreleaser. Not sure if that means documenting how to combine the autotag GH-action with goreleaser's own GH-action, or adding an optional step that supports goreleaser manually in our GH-action.

**Comment by vtopc** [comment]
Shouldn't we use/fork something like https://github.com/marketplace/actions/github-tag-bump instead?
