### ISSUE TITLE
update to latest git-module version

### ISSUE THREAD

**Issue by jburianek** [pantheon-systems/autotag#61]
We're currently running `git-module` version `v0.8.3`: https://github.com/pantheon-systems/autotag/blob/master/go.mod#L9

We should update to the latest one (currently it's `v1.1.5`): https://github.com/gogs/git-module/releases

Note that this has some breaking changes to the API that we'll need to resolve.

**Comment by joemiller** [comment]
related, @dependaot tried to do the upgrade too - #67
