### ISSUE TITLE
Latest release does not recognize "!" in commit message

### ISSUE THREAD

**Issue by rparulkar** [pantheon-systems/autotag#72]
**Issue**
Fails to recognize "!" as a breaking change and does not follow Semantic Versioning scheme. Results in MINOR bump instead of MAJOR. Introduced to this issue using the latest release but after further investigation tracked the genesis of the issue to **release 1.3.14**. The final 2 screenshots show release 1.3.13 working as expected.

**To Reproduce**
I created a dummy repo and attempted to replicate commits that helped discover the issue in the first place.

**Expected Behavior**
MAJOR version bump when the commit in question, latest commit, contains "!" in the message indicating a breaking change as in v.1.3.13 and prior. 

**Screenshots/Logs**
In order to replicate I did a series of basic and more complicated commits with different keywords that may trigger a particular versioning rule.

<img width="891" alt="Screen Shot 2022-01-20 at 10 49 42 AM" src="https://user-images.githubusercontent.com/42899593/150405618-ffbfe390-deed-4356-a726-d8faa81e2cc0.png">

The simple, 1 commit squash and merge PRs seem to be working correct. The commit at the top mimics the squash and merge PR that first introduced the issue. The expectation is that the tag should be 4.0.0, not 3.1.0. The tagging for the git log above was using the **latest release** of autotag. 

**Commit parsing in 1.3.14**

<img width="1137" alt="Screen Shot 2022-01-20 at 11 12 06 AM" src="https://user-images.githubusercontent.com/42899593/150406730-8de58b59-62bb-434e-a5ee-dfbaf0bf4e2f.png">

**Commit parsing in 1.3.13**

<img width="1153" alt="Screen Shot 2022-01-20 at 11 15 08 AM" src="https://user-images.githubusercontent.com/42899593/150406871-0a57778b-27ab-4f3d-965b-131401f540e4.png">

It appears the sequential order of parsing commits in v1.3.14 is reverse that of v1.3.13, potentially making the versioning bump not use the latest commit?

**System**
macOS using latest release as the introduction to bug

**Comment by spheromak** [comment]
Thanks for the report we will look into it.

**Comment by spheromak** [comment]
@rparulkar what version of git is being used here ?

**Comment by rparulkar** [comment]
2.33.0

**Comment by spheromak** [comment]
PR up for fix in #73 we should get that shipped out in a day or 2
